AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Resources for hosting a static website on Amazon Simple Storage Service (S3) & CloudFront.

Parameters:
  tableDemo:
    Type: String
    Description: test table domain
    Default: test-table-dynamo
    
Resources:
  CatalogEcTable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: !Ref tableDemo
        AttributeDefinitions:
        - AttributeName: typeDoc
          AttributeType: S
        - AttributeName: parentId
          AttributeType: N 
        KeySchema:
        - AttributeName: typeDoc
          KeyType: HASH
        - AttributeName: parentId
          KeyType: RANGE  
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        SSESpecification:
          SSEEnabled: true