AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Resources for hosting a static website on Amazon Simple Storage Service (S3) & CloudFront.
Resources:
  TheCloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "cloudfront de  intermediarios-dev.liberty.ec"

  TheBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: 'intermediarios-dev.liberty.ec'
      PolicyDocument:
        Statement:
          -
            Action:
              - s3:GetObject
            Effect: Allow
            Resource: Fn::Join [ "", [ "arn:aws:s3:::", 'intermediarios-dev.liberty.ec', "/*" ] ]
            Principal:
              CanonicalUser: Fn::GetAtt TheCloudFrontOriginAccessIdentity.S3CanonicalUserId        
        
Outputs:
  accessIdentity:
    Value: 
        Fn::GetAtt TheCloudFrontOriginAccessIdentity.Arn
    Description: arn of lambda intllatamecsendmassivemail
    Export:
        Name: "TheCloudFrontOriginAccessIdentity"